apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-51
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-51
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-6
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-6
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-53
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-53
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-54
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-54
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-55
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-55
    importPolicy: {}
    referencePolicy:
      type: Local
