apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-46
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-46
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-47
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-47
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-48
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-48
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-49
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-49
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-50
    from:
      kind: DockerImage
      name: quay.io/isanchez/iot-consumer:0.3.2-50
    importPolicy: {}
    referencePolicy:
      type: Local
