main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: isanchez
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: drhelius
    username: drhelius
    email: isanchez@redhat.com
    dev_revision: main

  s3:
    bucket:
      name: S3BUCKETNAME
      region: AWSREGION
      message:
        aggregation:
          count: 100
      custom:
        endpoint:
          enabled: false
