global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: drhelius
    username: drhelius
    email: isanchez@redhat.com
    dev_revision: main

  quay:
    provider: quay.io
    account: isanchez

  datacenter:
    clustername: isanchez
    domain: sandbox582.opentlc.com

  edge:
    clustername: isanchez
    domain: sandbox582.opentlc.com

